openapi:  3.0.3
info:
  title:  Echo Service - Python REST API
  version:  1.0.0
servers:
  - url: "{server}:{port}/main"
    variables:
      server:
        default: http://localhost
      port:
        default: "8090"
paths:
  /health:
    get:
      summary: Health Check
      operationId: healthCheck
      responses:
        "200":
          description: Successful operation
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/StringArray'
  /echo:
    post:
      summary: Echo test
      operationId: EchoService
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
      responses:
        "200":
          description: Echoed text response
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    ErrorPayload:
      type: object
      properties:
        reason:
          type: string
          description: Reason phrase
        path:
          type: string
          description: Request path
        method:
          type: string
          description: Method type of the request
        message:
          type: string
          description: Error message
        timestamp:
          type: string
          description: Timestamp of the error
        status:
          type: integer
          description: Relevant HTTP status code
          format: int32
    EchoRequest:
      required:
        - text
      type: object
      properties:
        text:
          type: string